#!/usr/bin/env bash
# host on a network

if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
else if [ $# -gt 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
else
	ping "$1" -c 5
fi
